// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijxqfmifhtwgoqarrbkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeHFmbWlmaHR3Z29xYXJyYmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTI0MjIsImV4cCI6MjA2NTYyODQyMn0.71HJgJZHF3DhV11Z4h15bNVOTXKCSPOUfJGPZLs8Arg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);